### ISSUE TITLE
Support / Package for Spark 3.1.2

### ISSUE THREAD

**Issue by hivemind-julius** [leobenkel/ZparkIO#148]
Hey there :wave:  and thanks for this nice library :+1: 

Do you plan to create a version for spark `3.1.2`? Would be happy to have it :-)

Kind regards

**Comment by hivemind-julius** [comment]
@leobenkel have you looked into #138 ?

**Comment by leobenkel** [comment]
oh I am so sorry, I must have missed the notification. I merged the PR.
