### ISSUE TITLE
CLI - Scallop

### ISSUE THREAD

**Issue by leobenkel** [leobenkel/ZparkIO#54]
Put Scallop specific code in its own component and make the default version more generic

**Comment by DamianReeves** [comment]
I can take a look at this.

**Comment by leobenkel** [comment]
i would recommend doing those:
- create a dummy project using today's set up
- test `--help`
- look at the log which described the used commands
- access arguments from the application using the snippet of code below (the object Arguments)
- test passing a wrong command line
- try to access it in https://github.com/leobenkel/ZparkIO/blob/95de593a5463486b18f7196e225f18f2d0a070dd/Library/src/main/scala/com/leobenkel/zparkio/Services/SparkModule.scala#L31 to add a `spark.option(...)`
- then, try removing scallop from build.sbt and from https://github.com/leobenkel/ZparkIO/blob/95de593a5463486b18f7196e225f18f2d0a070dd/Library/src/main/scala/com/leobenkel/zparkio/Services/CommandLineArguments.scala#L18
- replace what breaks by un-implmented methods in the trait
- create a new module with scallop to cut and paste the previous implementation into this isolated module
- go back to your dummy project and add the zparkio library as well as the zparkio-scallop library. it should work the same way
- copy your dummy project and try to make it work with an other config library.



How to use CommandLine today:
```scala
class Arguments(override val args: Seq[String])
    extends ScallopConf(args) with CommandLineArguments.Service {
...
}

object Arguments {
  type ArgumentEnv = CommandLineArguments.CommandLineArguments[Arguments]

  def apply(): ZIO[ArgumentEnv, Throwable, Arguments] =
    CommandLineArguments.apply[Arguments]()

  def apply[A](f: Arguments => A): ZIO[ArgumentEnv, Throwable, A] =
    CommandLineArguments.get[Arguments].map(_.apply(f))
}
```

which allow to do :
```scala
for {
   path <- Arguments(_.readPath)
   ds <- readUserFrom(path)
} yield ds
```
