### ISSUE TITLE
Project Example is returning Github 404 and support for spark 3.0

### ISSUE THREAD

**Issue by luancaarvalho** [leobenkel/ZparkIO#84]
Hello, in the Readme when I click in Project Exampl/Project Example Application, the return is a 404 Github Page:
![image](https://user-images.githubusercontent.com/34407796/102386035-54d3f080-3fad-11eb-95a5-b018fb464171.png)

Lastly, do you have plans to support spark 3.0 ?

**Comment by leobenkel** [comment]
Thank you for noticing those links. It is now fix.

Related to Spark 3.0, I havent looked into it yet. It would be interesting to try. 
Should just be a matter of adding it there : https://github.com/leobenkel/ZparkIO/blob/main/sparkVersions
