### ISSUE TITLE
CI pipeline

### ISSUE THREAD

**Issue by leobenkel** [leobenkel/ZparkIO#88]
Move away from TravisCI and find a new CI/CD pipeline that is more reliable.

Travis has blocked all the pipeline right now , it allows open source project to have limited resources but they have not answered my requests for the projects to be marked as open source.

**Comment by leobenkel** [comment]
@fakirAyoub do you have experience with CircleCI ?

**Comment by z4f1r0v** [comment]
https://github.com/leobenkel/ZparkIO/pull/96

**Comment by z4f1r0v** [comment]
@leobenkel and I agreed that we will simplify the release flow to release every successful merge to `main`. We are leaving it as a `TODO` to release and promote SNAPSHOTS to a stable releases.

**Comment by leobenkel** [comment]
`TODO` : bring back the mutator testing in the CI pipeline

**Comment by z4f1r0v** [comment]
> @leobenkel and I agreed that we will simplify the release flow to release every successful merge to `main`. We are leaving it as a `TODO` to release and promote SNAPSHOTS to a stable releases.

SNAPSHOTS have been preserved :)
